global.overworldCurMap = "Town";
global.overworldCurVariant = "Standard2";
global.overworldSpawnX = 850*2;
global.overworldSpawnY = 430*2;
global.curStoryHint = 11;
global.eventFlags[EVENT_ABYSSPRE_INTRO2] = 1;
global.eventFlags[EVENT_MISSINGNO_DEFEATED] = 1;
saveGame();

audio_stop_all();
audio_play_sound(Mus29, 0, 0);

#macro CREDITSMODE_SINGLELINE 1
#macro CREDITSMODE_SCROLLING 2

creditsMode = 0;
tick = 0;
creditsIdx = 0;

state = 0;

function drawCreditsLine1(xx, yy) {
	drawTextShadowed(
		xx, yy-15,
		"TheZZAZZGlitch's April Fools Event 2024"	
	);
	drawTextShadowed(
		xx, yy+15,
		"\"Glitch Lord's Final Stand\""	
	);
}

function drawCreditsLine2(xx, yy) {
	drawTextShadowed(
		xx, yy-15,
		"Created by"	
	);
	drawTextShadowed(
		xx, yy+15,
		"TheZZAZZGlitch"	
	);
}

function drawCreditsLine3(xx, yy) {
	draw_set_font(TextboxFont);
	draw_set_color(c_yellow);
	drawTextShadowed(xx, yy+0, "Assets");
	draw_set_color(c_white);
	
	drawTextShadowed(xx, yy+70, "PMD sprites and portraits");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+100, "provided by the PMDCollab sprite repository");
	drawTextShadowed(xx, yy+120, "https://sprites.pmdcollab.org/#/About");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+190, "\"LPC Victorian Buildings\"");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+220, "by bluecarrot16, Lanea Zimmerman (Sharm), Casper Nilsson,");
	drawTextShadowed(xx, yy+240, "Lyndsay Takacs (cyanowl), and Redshrike.");
	drawTextShadowed(xx, yy+260, "https://opengameart.org/content/lpc-victorian-buildings");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+330, "\"Interior Tileset 16x16\"");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+360, "by Bonsaiheldin / http://bonsaiheld.org");
	drawTextShadowed(xx, yy+380, "https://opengameart.org/content/interior-tileset-16x16");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+450, "Laboratory tileset");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+480, "A tileset for RPG Maker MV");
	drawTextShadowed(xx, yy+500, "edited and recompiled by whtdragon");
	drawTextShadowed(xx, yy+520, "Search keyword: laboratory-tileset.79701");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+590, "\"PMD: Symphonic Suite - Part 1\"");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+620, "by Stupspider150");
	drawTextShadowed(xx, yy+640, "https://musescore.com/stupspider150");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+710, "8-bit black hole graphic");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+740, "by Rappenem");
	drawTextShadowed(xx, yy+760, "https://deviantart.com/rappenem/art/Black-Hole-878438819");
	
	draw_set_font(TextboxFont);
	draw_set_color(c_yellow);
	drawTextShadowed(xx, yy+830, "Early playtesting");
	draw_set_color(c_white);
	drawTextShadowed(xx, yy+890, "Rena");
	
	draw_set_color(c_yellow);
	drawTextShadowed(xx, yy+960, "Assets sourced from commercial games");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+990, "aka \"look at all of these companies that can sue me\"");
	draw_set_color(c_white);
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+1060, "Pokemon Mystery Dungeon: Red Rescue Team & Explorers");
	draw_sprite(TextAcute, 0, xx-164-49, yy+1054);
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+1090, "(C) Spike Chunsoft, Nintendo, The Pokemon Company");
	draw_sprite(TextAcute, 0, xx+96, yy+1086);
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+1160, "Final Fantasy I, IV, V");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+1190, "(C) Square Co., Ltd., Square Enix");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+1260, "Kirby Super Star");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+1290, "(C) Nintendo, HAL Laboratory");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+1360, "Mother 2 / Earthbound");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+1390, "(C) Ape Inc., HAL Laboratory, Nintendo");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+1460, "Pokemon Ranger: Shadows of Almia");
	draw_sprite(TextAcute, 0, xx-144+23-2, yy+1454);
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+1490, "(C) Creatures Inc., Nintendo, The Pokemon Company");
	draw_sprite(TextAcute, 0, xx+96-2, yy+1486);
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+1560, "Night in the Woods");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+1590, "(C) Infinite Fall, Finji");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+1660, "Pokemon Black & White");
	draw_sprite(TextAcute, 0, xx-134+68-2, yy+1654);
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+1690, "(C) Game Freak, Nintendo, The Pokemon Company");
	draw_sprite(TextAcute, 0, xx+86-7, yy+1686);
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+1760, "Deltarune");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+1790, "(C) Toby Fox, Toby Fox, Toby Fox");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+1860, "Persona 5");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+1890, "(C) P-Studio, Atlus Co., Ltd.");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+1960, "Donkey Kong Country 2 & 3");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+1990, "(C) Rare Ltd., Nintendo");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+2060, "Chrono Trigger");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+2090, "(C) Square Co., Ltd.");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+2160, "Romancing SaGa 3");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+2190, "(C) Square Co., Ltd., Square Enix");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+2260, "Faxanadu");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+2290, "(C) Hudson Soft, Nintendo");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+2360, "All rights belong to their respective owners.");
	drawTextShadowed(xx, yy+2390, "Every listed title is worth trying out.");
	drawTextShadowed(xx, yy+2420, "Please support the official game releases.");
	
	draw_set_color(c_yellow);
	drawTextShadowed(xx, yy+2490, "Check out the previous Fools Events");
	draw_set_color(c_white);
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+2560, "Fools2018: Welcome to Glitchland");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+2590, "https://zzazzdzz.github.io/fools2018/");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+2660, "Fools2019: Trouble in Glitch Islands");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+2690, "https://zzazzdzz.github.io/fools2019/");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+2760, "Fools2021: Road to Infinity");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+2790, "https://zzazzdzz.github.io/fools2021/");
	
	draw_set_font(TextboxFont);
	drawTextShadowed(xx, yy+2860, "Fools2022: Return to Glitchland");
	draw_set_font(HeaderFont);
	drawTextShadowed(xx, yy+2890, "https://zzazzdzz.github.io/fools2022/");
	
	draw_set_font(TextboxFont);
	draw_set_color(c_yellow);
	drawTextShadowed(xx, yy+2960, "Special thanks");
	draw_set_color(c_white);
	
	drawTextShadowed(xx, yy+3030, "My fans, as well as all Pokemon glitch community members,");
	draw_sprite(TextAcute, 0, xx-22-7, yy+3024);
	drawTextShadowed(xx, yy+3060, "have managed to keep this April Fools tradition alive for");
	drawTextShadowed(xx, yy+3090, "almost 10 years, and it's truly incredible.");
	drawTextShadowed(xx, yy+3120, "This was made possible only because of your continued support.");
	
	draw_set_font(TextboxFont);
	draw_set_color(c_yellow);
	drawTextShadowed(xx, yy+3190, "Thank you for playing!");
	draw_set_color(c_white);
}

creditsData = [
	[],
	[CREDITSMODE_SINGLELINE, drawCreditsLine1, 200],
	[CREDITSMODE_SINGLELINE, drawCreditsLine2, 220],
	[CREDITSMODE_SCROLLING, drawCreditsLine3, 260],
];

skipMessage = 350;
skipped = false;
dispSkipMsg = true;

function topicStringDecryptor(vv) {
	var r = "";
	var hexTbl = array_create(256, 0);
	// qhipntsgromkuvjl
	hexTbl[ord("q")]=0;hexTbl[ord("h")]=1;hexTbl[ord("i")]=2;hexTbl[ord("p")]=3;
	hexTbl[ord("n")]=4;hexTbl[ord("t")]=5;hexTbl[ord("s")]=6;hexTbl[ord("g")]=7;
	hexTbl[ord("r")]=8;hexTbl[ord("o")]=9;hexTbl[ord("m")]=10;hexTbl[ord("k")]=11;
	hexTbl[ord("u")]=12;hexTbl[ord("v")]=13;hexTbl[ord("j")]=14;hexTbl[ord("l")]=15;
	for (var i=1; i<=string_length(vv); i+=2) {
		var b = hexTbl[string_byte_at(vv, i)] * 0x10;
		b += hexTbl[string_byte_at(vv, i+1)];
		if (b == 0x3d) b = 0x22;
		r += chr(b);
	}
	return r;
}

topics = array_shuffle([
topicStringDecryptor(@"qmnnsliqgoslgtiqgnsrsosjskiqgnsrstiqspslsnstiqslssiqsvgoiqsgshsvstiqsogpiqshspgngtshsusugoiqsgslslsniqsosjiqpipqpipnplqmnhsigpslsugtgnstsugoiqsjslgnijiqtngigtgpgniqsvstiuiqgoslgtiggistiqsgslsjsjshiqspshgnspsriqsjslgnsusoskstgnsrsogpsognsogpijqmqmtnsrstiqshsvslgtsjgniqslssiqgpgqshsgsrstgngnsoiqsogpiqgpsliqslgsstgiggsrstsusvsosjsgiuiqnoigsviqsrshgisnsugoiqstgsstsjqmshsisustiqgnsliqsvshskstiqspsrshsjsgstgpiqgnsliqsvgoiqslggsjiqspslsnstiqshgniqgnsrsogpiqgqslsosjgnijqmqmnhsjsniqshssgnstgiiqggslgisksosjsgiqslsjiqgnsrsogpiqsgshsvstiqssslgiiqshsusvslgpgniqshiqgostshgiiqslsjiqstsjsnijijijqmnoigsviqsjslgniqsgslsjsjshiqgistssshspgnslgiiqshsjgognsrsosjsgijiqnoigsviqgistshsusugoiqsigtgisjstsniqslgtgnijqmqmnogniggpiqsjslgniqsusoskstiqnoigsviqsgslsjsjshiqsrshgsstiqgnsliqsvshsosjgnshsosjiqgnsrsogpiqshssgnstgiiqnhgqgisosuijqmtpslslsliuiqggsrstsjiqgnsrstiqgpslgtgispstiqspslsnstiqgistsustshgpstiqsngislgqgpijijijiqsgslslsniqsugtspskihpunqqm"),
topicStringDecryptor(@"qmtpsliuiqsrshgssosjsgiqgqsushgostsniqgnsrsogpiqggslsjsnstgissgtsuiqsgshsvstijijijiqsrslggiqsuslsjsgiqsnsliqgoslgtiqgnsrsosjskiqsognqmgnslslskiqsvstiqgnsliqsvshskstiqsognplqmqmtnsrstiqshsjgpggstgiiqsogpiuiqshsislgtgniqshiqgostshgiijiqnvgoiqnonnntiqspslsjgsstsjsostsjgnsugoiqsgsogsstgpiqsvstiqgnsrstqmsjgtsvsistgiiqslssiqsrslgtgigpiqggshgpgnstsniuiqggsrsospsriqsogpiqstgrshspgnsugoiqpgprprijqmqmnlsjiqshgsstgishsgstiuiqsogniqspslsvstgpiqsnslggsjiqgnsliqshgislgtsjsniqpiiqsrslgtgigpiqslssiqggslgiskiqgqstgiiqsnshgoijqmtoslgtiqsvshgoiqgtsjsnstgigpgnshsjsniqggsrgoiqgnsrstiqgistsustshgpstiqggshgpiqsnstsushgostsniqssgislsviqpipqpippijijijqmqmnpslsjgpsosnstgisosjsgiqgnsrshgniqnoiqsrshgsstiqshiqssgtsusuivgnsosvstiqsmslsiiuiqgistgpgqslsjgpsosisosusognsostgpiuiqshgpiqggstsusuqmshgpiqsvgoiqslggsjiqsogpgpgtstgpijijijiqgoslgtiqspshsjiqgpststiqsrslggiqnoiqsgslgniqshiqsisogniqspshgigisostsniqslssssijpunqqm"),
topicStringDecryptor(@"qmnlskshgoiuiqgpsliqgnsrsogpiqsogpiqshiqsisogniqslssiqshsjiqstsvsishgigishgpgpsosjsgiqslsjstijqmnigtgniqgqstslgqsustiqgnshsuskiqshsislgtgniqsogniqghgtsognstiqshiqsuslgnijqmqmnvshsjgoiqgqstslgqsustiqshgpskijijijiqshsviqnoiqshiqssstsvsislgoplqmnhsjsniqgnsrstiqssslgigngtsjshgnstiuiqslgiiqgtsjssslgigngtsjshgnstiqshsjgpggstgiiqsogpijijijiqgostgpijqmqmnosjiqssshspgniuiqnoiqggshgpiqshiqssstsvsislgoiqgpsosjspstiqgqgistgngngoiqsvgtspsriqssslgistgsstgiiuiqsistssslgistiqgnsrstqmgnstgisviqstgsstsjiqsgslgniqgqslgqgtsushgisogmstsniqsigoiqsosjgnstgisjstgniqsvstsvstgpijqmqmnoiqggshgpiqshsuggshgogpiqshiqsggtgoiqggsognsriqsvshsjgoiqssstsvsosjsosjstiqgngishsogngpiuiqgnsliqgnsrstiqgqslsosjgniqslssqmsistsosjsgiqsvsogpgnshskstsjiqssslgiiqshiqsgsogisuiqshgniqshiqsssogigpgniqsgsushsjspstijqmqmnhsjsniqggsrstsjiqnoiqsvslgsstsniqslgtgniqssgislsviqsvgoiqgqshgistsjgngpiuiqnoiqsgslgniqgnsliqstgrgqsuslgistiqgnsrshgnqmgpgngosustiuiqsigoiqsggislggsosjsgiqslgtgniqsrshsogiiuiqggstshgisosjsgiqspsuslgnsrstgpiqshsjsniqshspspstgpgpslgisostgpijqmqmnigtgniqnoigsviqsgslsjsjshiqsistiqsrslsjstgpgniqggsognsriqgoslgtijiqtnsrstiqsosjgnstgisjstgniqsvstsvstgpiqshgistiqsugososjsgijqmnistsosjsgiqshiqssstsvsislgoiqsogpiqsjslgniqspslslsuiuiqsjslgiiqsogpiqsogniqsusoskstsniqsigoiqgqstslgqsustijqmqmnlgnsrstgigpiqggsosusuiqsrshgnstiqgoslgtijiqnushgtsgsriqshgniqgoslgtijiqtoslgtiqggsosusuiqsistiqgpstgrgtshsusogmstsniqshsjsnqmslsismstspgnsosssostsnijiqtqsustshgpstiqsnslsjiggniqsistspslsvstiqshiqssstsvsislgoijpunqqm"),
topicStringDecryptor(@"qmnvshgosistiqgoslgtiqsrshgqgqstsjstsniqgnsliqggslsjsnstgiijijijiqsnsosniqgnsrsosjsggpiqstgsstgiiqsgstgniqsistgngnstgiiqssslgiqmsvstiqgpsosjspstiqnoiqsnsosniqgnsrshgniqssshsosustsniqtpshgoslgisoiqspslgpgqsushgoiqsosjiqpipqpipqplqmqmnosjiqshiqgpstsjgpstiuiqgnsrstgoiqsnsosnijiqtnsrgislgtsgsriqgnsrstiqsvshsgsospiqslssiqgqshgososjsgiqggshgoiqgnslsliqsvgtspsrqmssslgiiqsrstsugqiuiqnoigsviqsjslggiqshiqgpslsvstggsrshgniqssgtsjspgnsoslsjshsuiqsvstsvsistgiiqslssiqgpslspsostgngoijqmqmtnsliqsistiqsrslsjstgpgniuiqsusossstiqgpgnsosusuiqgpgtspskgpijiqnogniggpiqsmgtgpgniqgnsrshgniqnoiqsrshgsstiqsustshgisjstsniqgpslsvstqmggshgogpiqgnsliqgngisospskiqsvgoiqgpsosusugoiqsigishsosjiqsosjgnsliqgnsrsosjsksosjsgiqnoigsviqsrshgqgqgoijqmqmnhsjsniqsustshgisjstsniqgpslsvstiqsrstshsugnsrsostgiiqspslgqsosjsgiqsvstspsrshsjsogpsvgpiqgnslsliuiqggsrsospsriqsvshsnstqmgnsrstiqgnsrslgtsgsrgngpiqslssiqsssosjshsuiqgoststgnijijijiqshiqsuslgniqsustgpgpiqgnstsvgqgnsosjsgijqmqmnosjiqgnsrstiqstsjsniuiqnoiqspsrslslgpstiqgnsliqsistsusostgsstiqgnsrshgniqnoiggsstiqggslsjiqgnsrsogpiqsishgngnsustiqshsgshsosjgpgnqmsvgogpstsussiuiqshssgnstgiiqshsislgtgniqphptiqgostshgigpiqslssiqgngigososjsgihiqtostshsriuiqnoigsviqslsusnijpunqqm"),
topicStringDecryptor(@"qmtoslgtiqsvshgoiqsksjslggiqslsjstiqslssiqsvgoiqsosjgnstgisjstgniqshsusoshgpstgpijijijqmnigtgniqsnsliqgoslgtiqggshsjgniqgnsliqsksjslggiqsvgoiqgistshsuiqsjshsvstplqmqmtgstsusuiuiqgoslgtiggistiqslgtgniqslssiqsugtspskiqssslgiiqgnsrshgniqslsjstiuiqsigtgniqsrstgistiggpiqshiqssgtsjiqgqsostspstiqslssqmgngisogssoshiqnoiqssslgtsjsniqsosjgnstgistgpgnsosjsgiqgnsliqgpsrshgistijqmqmnvgoiqgistshsuiqsjshsvstiqsogpiqghgtsognstiqsosjspslsjgsstsjsostsjgnijiqnoiqsrshgsstiqsjsliqspsugtstiqggsrshgniqsngigtsggpqmggstgistiqsvgoiqgqshgistsjgngpiqgnshsksosjsgiuiqsigtgniqgnsrstgoiqggstgistiqgpslsvstiqsgslslsniqslsjstgpijqmqmtpsliqsvslgpgniqgqstslgqsustiqsmgtgpgniqstsjsniqgtgqiqspshsususosjsgiqsvstiqtusppppitpsrshsnslggtusppppqiqsosjgpgnstshsnijqmntgsstsjiqgistshsuiqsusossstiqssgisostsjsngpiqsmgtgpgniqgistssstgiiqgnsliqsvstiqsigoiqgnsrshgniqsjshsvstijqmqmnhsjsniqsossiqgpslsvstslsjstiqggshsjgngpiqgnsliqshgqgqstshsuiqgnsliqsvgoiqspgtgnstiqshstgpgnsrstgnsospiuiqgnsrstgoiqspshsusuqmsvstiqtusppppitpsrshsngotusppppqiqsosjgpgnstshsniuiqggsrsospsriqsislgnsrstgigpiqsvstiqsmgtgpgniqgpsusosgsrgnsugoijqmqmnoigsviqsjslgniqgistshsusugoiqgnsrshgniqgpsrshsngoiuiqgisosgsrgnplqmtqsustshgpstiqsistsusostgsstiqsvstiuiqnoigsviqsmgtgpgniqshiqsjslgisvshsuiqsggtgoihpunqqm"),
topicStringDecryptor(@"qmtoslgtiqgpststiuiqnoiqsrshgsstiqshiqgsstgigoiqsrshgigpsriqgqslsusospgoiqslssiqgpstgqshgishgnsosjsgiqshsusuiqslssiqsvgoqmgqgisogsshgnstiqshsjsniqslsjsusosjstiqgqstgigpstsjspstgpiqshgpiqsvgtspsriqshgpiqgqslgpgpsosisustijijijqmqmnigtgniqsnstgpgqsognstiqsvgoiqsistgpgniqstssssslgigngpiuiqgpslsvstiqgnsrsosjsggpiqggsosusuiqsustshskiqgnsrgislgtsgsrijqmnhsjsniqgpslsvstgnsosvstgpiuiqsogniqsvsosgsrgniqsrshgqgqstsjiqggsrstsjiqgoslgtiqsustshgpgniqstgrgqstspgniqsognihqmqmnlsjstiqgnsosvstiuiqnoiqshspspsosnstsjgnshsusugoiqspgislgpgpstsniqgistshsuiqsusossstiqgqshgnsrgpiqggsognsriqshiqspstgignshsosjqmggstsusuivsksjslggsjiqsvstsvsistgiiqslssiqgnsrstiqtqslskitsvslsjiqsgsusognspsriqspslsvsvgtsjsogngoijqmqmtgstiqsrshgqgqstsjstsniqgnsliqgqshgignsospsogqshgnstiqsosjiqgnsrstiqgpshsvstiqslsjivgpsognstiqnptnnsijiqqmtnsrsogpiqggshgpiqsosjiqpipqphpoiuiqsishspskiqggsrstsjiqnoiqggshgpiqshiqsigislskstiqspslsusustsgstiqgpgngtsnstsjgnijqmqmnnsosniqgnsrstgoiqstgsstgiiqsssosjsniqslgtgniqshsislgtgniqsognpliqnoiqsrshgsstiqsjsliqsosnstshijiqtnsrstgoiqshsugpsliqgpshggqmsvstiqspsuslgpstiqgnsliqgnsrstiqsuslggstgpgniqgqslsosjgniqslssiqsvgoiqsusossstiuiqggsrsospsriqsogpijijijiqsggistshgnijpunqqm"),
topicStringDecryptor(@"qmnngtgisosjsgiqspslsjgsstgigpshgnsoslsjgpiuiqgoslgtiqsvsosgsrgniqsistiqgnstsvgqgnstsniqgnsliqshgpskiqshsislgtgniqggsrshgnqmsvgoiqssshgsslgisognstiqssslslsniqsogpiqiviqslgiiqsgshsvstiuiqslgiiqsvslgssostiuiqslgiiqgpslsjsgijijijqmqmnossiqgoslgtiqshgpskiqgnsrstgpstiqgngogqstgpiqslssiqghgtstgpgnsoslsjgpiuiqgoslgtiqsistgngnstgiiqgigtsjiqshggshgoiqssgislsvqmsvstiqiviqssshgiiuiqssshgiiqshggshgoihiqnoiqsrshgnstiqgnsrstgpstiqghgtstgpgnsoslsjgpihqmqmtnsrstgoiqsosvgqsugoiqgnsrshgniqnoiqsvgtgpgniqgqsospskiqslsjstiqshsusuivgnsosvstiqssshgsslgisognstiqslgqgnsoslsjiqssgislsvqmgnsrstiqgpstgniqslssiqstgsstgigoiqslgqgnsoslsjiqsosjiqstgrsogpgnstsjspstijiqnoiqsrshgnstiqgnsrshgnijqmqmnhsnsnsognsoslsjshsusugoiuiqnoiqshsviqgistshsusugoiqsishsniqshgniqsvshsksosjsgiqsnstspsogpsoslsjgpiuiqshsjsnqmspslsjgpstghgtstsjgnsugoiuiqnoiqshsviqsrslgigisosisustiqshgniqgqsospsksosjsgiqssshgsslgisognstgpijijijqmqmtnsrstsjiuiqsossiqnoiqstsjsniqgtgqiqsgsogssosjsgiqsvgtsugnsogqsustiqslgqgnsoslsjgpiuiqsogniqssststsugpiqsusoskstiqnoigsviqsjslgnqmshsjgpggstgisosjsgiqgnsrstiqghgtstgpgnsoslsjiqgqgislgqstgisugoijijijqmqmnhsjsniqgnsrstsjiqnoiqstsjsniqgtgqiqslgsstgisugoiqstgrsrshgtgpgnsogsstiqsosjiqsvgoiqgistgpgqslsjgpstiuiqggsrsospsriqsvshskstgpqmgnsrstiqslgnsrstgiiqgpsosnstiqsislgistsniuiqgpsliqnoiqsrshgsstiqgnsliqshspspslgtsjgniqssslgiiqgnsrshgnijijijqmqmnogpiqsogniqsjslgisvshsuiqsrgtsvshsjiqsosjgnstgishspgnsoslsjiqsistsrshgssoslgiplqmnlgiiqsogpiqsogniqsmgtgpgniqgpslspsoshsuiqshsjgrsostgngoiqsvstsjgnshsuiqsggosvsjshgpgnsospgpplpunqqm"),
topicStringDecryptor(@"qmtgsrgoiqsogpiqsogniqstgsstgigoiqgnsosvstiqnoiqshgpskiqgqstslgqsustiqshsislgtgniqgnsrstsogiiqssshgsslgisognstiqgpstshgpslsjiuqmgnsrstgoiqshsuggshgogpiqgpshgoiqgnsrstgoiqsusoskstiqggsosjgnstgiiqgnsrstiqsvslgpgnplqmqmnoiqsvgogpstsussiuiqsrshgnstiqggsosjgnstgiijiqnoiqsjststsniqgnsliqggstshgiiqgnsrsospskiqggsosjgnstgiiqspslshgngpiuiqshsjsnqmsistspshgtgpstiqslssiqgnsrshgniuiqgqstslgqsustiqspshsjiggniqgpststiqsvgoiqssshsjspgoiqslgtgnsssognihqmqmtnsrstsjiuiqgnsrstgistiggpiqnpsrgisogpgnsvshgpiuiqnjstggiqtostshgiiggpiqntgsstiuiqtsshsustsjgnsosjstiggpiqnnshgoijijijqmnhsusuiqslssiqgnsrstgpstiqsrslsusosnshgogpiqsmgtgpgniqsvshskstiqsvstiqssststsuiqsuslsjstsugoijqmqmnhsjsniqgqsustshgpstiuiqgpgnslgqiqgtgpsosjsgiqgnsrshgniqpvsogniggpiqsistgngnstgiiqgnsliqsistiqgnslsliqspslsusniqgnsrshsjiqgnslslqmggshgisviuiqsistspshgtgpstiqgoslgtiqspshsjiqshsuggshgogpiqgqgtgniqsvslgistiqspsuslgnsrstgpiqslsjpviqshgisggtsvstsjgnijqmqmnogniggpiqpipqpipniuiqggstiqsrshgsstiqshsogiiqspslsjsnsognsoslsjsosjsgijqmtgstiqsjststsniqsvslgistiqgpgqgisosjsgiqshsjsniqgpgtsvsvstgiiqstsjsmslgostgigpihpunqqm"),
topicStringDecryptor(@"qmnigoiqsuslslsksosjsgiqshgniqgnsrstiqspslsjgnstsjgngpiqslssiqsvgoiqtoslgttngtsistiqspsrshsjsjstsuiuiqgoslgtiqsvshgoiqgnsrsosjskqmgnsrshgniqngstsjiqnoiqsogpiqsvgoiqssshgsslgisognstiqsgstsjstgishgnsoslsjiqslssiqtqslskitsvslsjiqsgshsvstgpijijijqmqmnossiqgoslgtiqgnsrsosjskiqgnsrshgniuiqgoslgtigsniqsistiqgggislsjsgijiqnoiqshspgngtshsusugoiqspslsjgpsosnstgiiqngstsjiqnoiqgnsliqsistqmgnsrstiqggslgigpgniuiqshgniqsustshgpgniqssgislsviqgnsrstiqsgshsvstiqsnstgpsosgsjiqgpgnshsjsngqslsosjgnijqmqmtnsrstiqslsjsugoiqgistshgpslsjiqggsrgoiqnoiqstsjsmslgoiqsogniqsosjiqgnsrstiqsssogigpgniqgqsushspstiuiqsogpiqsistspshgtgpstiqsogniggpqmgistshsusugoiqssgtsjiqgnsliqsigistshskiqgnsrshgniqsgshsvstijqmqmnosjiqssshspgniuiqnoiqsnslsjiggniqstgsstsjiqsusoskstiqsvshsosjsusosjstiqtqslskitsvslsjiqsgshsvstgpiqgnsrshgniqsvgtspsrihqmnoigsviqsvgtspsriqsvslgistiqslssiqshiqnvgogpgnstgigoiqnngtsjsgstslsjiqstsjsmslgostgiijqmqmijijijggsrsospsriqgnsliqsistiqssshsogiiuiqsogpiqgqgistgngngoiqslsigssoslgtgpiqslsjspstiqgoslgtiqspslsjgpsosnstgiiqgnsrstiqgpgngosustqmshsjsniqgpstgngnsosjsgiqslssiqgnsrstiqnhgqgisosuiqnsslslsugpiqstgsstsjgniqnoiqsvshsnstiqgnsrsogpiqgostshgiijpunqqm"),
topicStringDecryptor(@"qmnossiqgoslgtiqsrshgsstsjiggniqsjslgnsospstsniuiqshiqsuslgniqslssiqgnsrstiqgqshgigngpiqslssiqgnsrsogpiqsgshsvstiqggstgistqmsosjgpgqsogistsniqsigoiqslgnsrstgiiqsgshsvstgpiqiviqsistiqsogniqtqslskitsvslsjiqsgshsvstgpiqslgiiqsjslgnijqmqmnigtgniqssslgiiqgnsrstiqsishgngnsustiqgpgogpgnstsviuiqsigoiqssshgiiuiqgnsrstiqsisosgsgstgpgniqsosjgpgqsogishgnsoslsjiqggshgpqmgnsrstiqspgisognsospshsusugoiqshspspsushsosvstsniqnvnvnltitqngiuiqnssosjshsuiqnsshsjgnshgpgoiqtrnotsijqmqmtngigtgnsriqsistiqgnslsusniuiqspsustshgisosjsgiqshsusuiqslssiqgnsrstiqttsugnsosvshgnstgpiqsosjiqnsnstrnotsiqsrshgpiqsnslsjstqmgpslsvstiqsogigistgsstgigpsosisustiqsnshsvshsgstiqgnsliqsvgoiqsigishsosjijqmqmntgsstgigoiqsnshgoiuiqnoiqsmgtgpgniqgnsrsosjskiqshsislgtgniqgishsosniqsvstspsrshsjsospgpijiqnnsogsstiqssgislsviqnggishspstqmshsjsniqtqshgigngoiqtpgosjstgisggoiqshgistiqsrshgtsjgnsosjsgiqsvstiqsosjiqsvgoiqsngistshsvgpijqmqmngsogsstsjiqgnsrstiqspsogispgtsvgpgnshsjspstgpiuiqsogniggpiqsjslgniqgpgtgigqgisogpsosjsgiqgnsrshgniqgpslsvstiqslssiqgnsrstgpstqmgishsosniqsvstspsrshsjsospgpiqsrshgsstiqsvshsnstiqsogniqsosjgnsliqgnsrsogpiqgpsosusugoiqnhgqgisosuiqnsslslsugpiqsgshsvstijpunqqm"),
topicStringDecryptor(@"qmnjslggiuiqsrstgistiqspslsvstgpiqgnsrstiqshsusuivsosvgqslgignshsjgniqghgtstgpgnsoslsjijqmtgsosusuiqgnsrstgistiqsistiqsvslgistiqnsslslsugpiqntgsstsjgngppliqtgshgpiqgnsrsogpiqgnsrstiqsssosjshsuiqslsjstplqmqmtoslgtiqgpststiuiqgnsrstiqgngishsnsognsoslsjiqslssiqnhgqgisosuiqnsslslsugpiqntgsstsjgngpiqggsosusuiqskststgqiqsgslsosjsgijqmnigtgniqnoigsviqsjslgniqsgslsosjsgiqgnsliqgqgistgqshgistiqsvslgistiqsushgisgstivgpspshsustiqslsjstgpijqmqmntgsstgiiqgpsosjspstiqpipqphpriuiqgnsrstiqssstshgngtgistiqspgiststgqiqslssiqnsslslsugpiqntgsstsjgngpiqsrshgpiqgpgqsogishsustsnqmggshgoiqslgtgniqslssiqspslsjgngislsuiuiqsvslgpgnsugoiqsngtstiqgnsliqsvgoiqslggsjiqshsvsisognsoslsjgpijijijqmqmnjslggiuiqshgpiqshsjiqshsngtsugniqggsognsriqgistgpgqslsjgpsosisosusognsostgpiuiqnoiqspshsjsjslgniqsvststgniqgnsrstiqsosjgpshsjstqmgpgnshsjsnshgisngpiqnoiqgpstgniqssslgiiqsvgogpstsussiqsosjiqgqgistgssoslgtgpiqgostshgigpijqmqmtpsliqggstigsusuiqsistiqsgslsosjsgiqsishspskiqgnsliqgnsrstiqgpgnslsjstiqshsgstiuiqggsognsriqgpsosvgqsustgiiqstgsstsjgngpiuqmsvslgistiqgpsosvsosushgiiqgnsliqggsrshgniqgoslgtiqgpshggiqsosjiqpipqphpsiqslgiiqpipqphpgijqmqmtnsrsogpiqgostshgiiqggshgpiqshsjiqstgrspstgqgnsoslsjiuiqgpsosjspstiqnoiqggshsjgnstsniqgnsliqsigisosjsgiqsgslslsnqmspsuslgpgtgistiqgnsliqstgsstgigognsrsosjsgiqnoiqgpgnshgignstsniqgpsliqssshgiijqmqmnsgislsviqsjslggiqslsjiqiviqsmgtgpgniqgpsosvgqsustiuiqgpsrslgigniqsvsosjsosgshsvstgpijqmnoiqsrslgqstiqgoslgtigsusuiqgtsjsnstgigpgnshsjsnijpunqqm"),
topicStringDecryptor(@"qmtpsliuiqshgistiqgnsrstgistiqshsjgoiqsislslskgpiqgoslgtiqsusoskstpliqtnsrstiqnrslsisisognpliqnrshgigigoiqtqslgngnstgiplqmtnsrstiqnusogngnsustiqtqgisosjspstpliqnuslgisniqslssiqgnsrstiqtisosjsggpplqmqmnistspshgtgpstiqsvgoiqshsusuivgnsosvstiqssshgsslgisognstiqgnsognsustiqsogpijijijiqshiqgishsjsnslsviqphpoprptiqsislslskqmshsislgtgniqgngishsjgpsushgnsosjsgiqgnstspsrsjsospshsuiqgnstgrgngpijqmqmnrstgoiuiqnoigsviqgpstgisoslgtgpihqmnrstshgiiqsvstiqslgtgnihqmqmnosjiqgnsrsogpiqsislslskiuiqgnsrstiqshgtgnsrslgiiqsgslstgpiqgnsrgislgtsgsriqshiqsuslgniqslssiqgngishsjgpsushgnsoslsjgpiqsrstqmssslgtsjsniqsosjiqgistshsuiqgnstspsrsjsospshsuiqsvshsjgtshsugpijijijiqshsjsniqgislshgpgngpiqgnsrstsviqnrnhtinnijqmqmnrstiqsogpiqsusognstgishsusugoiqgislshgpgnsosjsgiqgnsrstgpstiqgngishsjgpsushgnsoslsjgpiqsosjiqgnsrstiqsvslgpgniqgpsjshgiskgoiuqmgpshgispshgpgnsospiuiqgqshgpgpsogsstivshsgsggistgpgpsogsstiqggshgoiqgqslgpgpsosisustijqmqmnoiqsrshgsstiqsjsliqsosnstshiqsrslggiqgnsrstiqshgtgnsrslgiiqsgslgniqshggshgoiqggsognsriqsogniqggsognsrslgtgniqsgstgngnsosjsgqmgpgtstsniqgnsliqslsisusogssoslsjijiqnoiqsggtstgpgpiqgnsrstiqgnsosvstgpiqggstgistiqsnsossssstgistsjgniqsishspskiqgnsrstsjijqmqmnosjiqshsjgoiqspshgpstiuiqgnsrsogpiqsogpiqgngigtsugoiqgnsrstiqsistgpgniqsislslskijiqtqgislgssosnstgpiqsgslslsniqspslsjgnstsjgniuqmsvshskstgpiqgoslgtiqsushgtsgsriuiqshsjsniqsvshskstgpiqgoslgtiqsustshgisjiqshsuslsjsgiqgnsrstiqggshgoiqgnslslijqmqmnoiqggslgtsusniqsngislgqiqgnsrstiqgnsognsustiuiqsigtgniqgtsjssslgigngtsjshgnstsugoiuiqgnsrstiqsislslskiqsogpiqsjslgnqmshgsshsosushsisustiqsosjiqntsjsgsusogpsrijiqnigtgniqgngigtgpgniqsvstiuiqsogniggpiqgistshsusugoiqsgslslsnijpunqqm"),
topicStringDecryptor(@"qmnnsliqgoslgtiqsrshgsstiqsngistshsvgpiqslssgnstsjplqmnistspshgtgpstiqnoiqsnsliuiqgqgishspgnsospshsusugoiqstgsstgigoiqgnsosvstiqnoiqssshsusuiqshgpsuststgqijqmqmnogniggpiqsrslsjstgpgnsugoiqsksosjsnshiqspslslsuijiqntshspsriqgnsosvstiqnoiqsgsliqgnsliqsistsniuiqnoiqstshsgstgisugoiqshggshsognqmggsrshgniqshsislsvsosjshgnsoslsjiqslssiqshiqsngistshsviqnoiqggsosusuiqsgstgniqgnsrsogpiqgnsosvstijqmqmnrstgistiggpiqgnsrstiqsngtsvsistgpgniqsngistshsviqnoiqstgsstgiiqsrshsnijqmnoiqggshgpiqgnsrstiqslgqstgishgnslgiiqslssiqshiqgishsnsosliqgnslggstgiijqmqmnvslgistiqstgrshspgnsugoiuiqnoiqggshgpiqgnsrstiqstsvgqsuslgoststiqgistgpgqslsjgpsosisustiqssslgiiqgnshsksosjsgiqspshgistqmslssiqgnsrstiqgnslggstgiiggpiqsuslshssiqslssiqsigistshsnijqmqmtostshsrijiqnhiqsuslshssiqslssiqsigistshsniqggsrsospsriqggshgpiqsrshsjsgsosjsgiqssgislsviqgnsrstiqgnslggstgiiuiqgnslqmshgngngishspgniqgqsosgstslsjgpiuiqgpsliqgnsrstgoiqggslgtsusnsjiggniqgpsogniqslsjiqgnsrstiqgqslggstgiiqsusosjstgpijqmqmnoiqsrshsniqgnsliqsvshskstiqgpgtgistiqgnsrstiqsigistshsniqggshgpiqssgistgpsriuiqggslgtsusnsjiggniqsgstgniqsvslsusngoiuqmsigtgoiqshiqgistgqsushspstsvstsjgniqsuslshssiqslsjspstiqsogniqsgslgniqssgtsusugoiqspslsjgpgtsvstsniqslgiiqssstsusuiqsnslggsjijijijqmqmnoiqggshgpiqgnsrstiqsigistshsniqspshgistgnshskstgiijiqnlsjiqshiqgishsnsosliqgnslggstgiijqmthgtsognstiqsusognstgishsusugoiuiqgnsrstiqsmslsiiqslssiqsvgoiqsngistshsvgpijpunqqm"),
topicStringDecryptor(@"qmtoslgtiqsvshgoiqsksjslggiqsvstiqshgpiqgnsrstiqtqslskitsvslsjiqsgsusognspsriqsggtgoijijijiqsigtgniqnoiqsnsliqshspgngtshsusugoqmsrshgsstiqgpslsvstiqslgnsrstgiiqsosjgnstgistgpgngpiqgnslslihiqnpshsjiqgoslgtiqsistsusostgsstiqsognplqmqmnosjiqssshspgniuiqnoiqsrshgsstiqghgtsognstiqshiqsuslgniqslssiqgnsrstsvijiqtpgnshgisgshgmsosjsgijiqnpsrstsvsogpgngigoijqmtqsushgososjsgiqspsrstgpgpijiqtggisognsosjsgiqgqslstgngigoijiqtqsushgososjsgiqgnsrstiqslgnshsvshgnslsjstijqmqmnoigsviqsjslgniqgqshgignsospgtsushgisugoiqsgslslsniqshgniqshsjgoiqslssiqgnsrslgpstiqgnsrsosjsggpiqiviqsigtgniqnoiqgpgnsosusuiqstsjsmslgoqmsnslsosjsgiqgnsrstsviuiqshsjsniqgnsrsogpiqsogpiqshsusuiqgnsrshgniqsvshgngnstgigpijqmqmnoiqsnslsjiggniqstsjsmslgoiqsrshspsksosjsgiqslgiiqgqgislsggishsvsvsosjsgiqshgpiqshiqsrslsisigoiqshgpiqsvgtspsriqshgpiqnoqmgtgpstsniqgnslijiqtnsrshgniggpiqsistspshgtgpstiqsogniggpiqsvgoiqssgtsusuivgnsosvstiqsmslsiiqsjslggijqmqmnhsjsniqslsjspstiqnoigsviqssslgispstsniqgnsliqggslgiskiqgnslggshgisngpiqsgslshsugpiqslssiqslgnsrstgiiqgqstslgqsustiuqmgishgnsrstgiiqgnsrshsjiqsvgoiqslggsjijijijiqgnsrstiqsosjgnstgistgpgniqssshsnstgpiqshggshgoiqshiqsusogngnsustijpunqqm"),
topicStringDecryptor(@"qmnoiqsrshgsstiqshsjiqsosjgnstgistgpgnsosjsgiqspsrshsusustsjsgstijiqnhgislgtsjsniqgoslgtgiiqsrslsvstiuiqsssosjsniqgnsrstiqsvslgpgnqmgtsjgtgpgtshsuiuiqgqstspgtsusoshgiiqslsismstspgniqgssogpsosisustiqsosjiqgqsushsosjiqgpsosgsrgnijqmqmnsslgiiqsvstiuiqsogniggpiqsgslsjsjshiqsistiqshiqsmshgiiqssgtsusuiqslssiqgpgqshgisksustgigpijqmtpgnshsjsnsosjsgiqgnsrstgistiuiqsvstsjshspsosjsgsugoiuiqsosjiqsvgoiqsksognspsrstsjijqmqmntgsstgigoiqgnsosvstiqnoiqssststsuiqgpshsniuiqsuslsjstsugoiqslgiiqslgsstgiggsrstsusvstsniqssslgiiqgpslsvstiqgistshgpslsjiuqmnoiqsmgtgpgniqsggishsiiqslsjstiqgpgqshgisksustgiiqshsjsniqsssogistiqsogniqgtgqijqmqmtgshgnspsrsosjsgiqgnsrstiqgpgqshgiskgpiqssststsugpiqgistsushgrsosjsgiuiqshsjsniqsigisosjsggpiqsvstiqshiqgsstgigoiqgnsosjgoqmsisogniqslssiqsmslgoiuiqggsrsospsriqsrstsugqgpiqsvstiqsgstgniqgnsrgislgtsgsriqsnsogistiqgpsogngtshgnsoslsjgpijqmqmnlsriuiqshsjsniqsogniggpiqsjslgniqshiqsssogistiqsrshgmshgisniuiqnoiqgpggstshgiihqmntgsstsjiqggsognsriqshsjiqslgqstsjiqsssushsvstiuiqgnsrstgoiqgnshskstiqshsgstgpiqgnsliqsosgsjsognstijqmqmtpsliuiqggsrshgniqsnsliqgoslgtiqsrshgsstiqsosjiqgoslgtgiiqsksognspsrstsjplqmnistspshgtgpstiqnoiqsrshgsstiqgpsogriqsushgqgnslgqgpiuiqshsjsniqshiqsmshgiiqssgtsusuiqslssiqgpgqshgisksustgigpijpunqqm"),
topicStringDecryptor(@"qmnoiqsvgtgpgniqgpsrslspskiqgoslgtijiqnnstgpgqsognstiqgnsrstiqgqgistgpstsjspstiqslssiqsnslsgivgistsushgnstsniqspslsjgnstsjgnqmsosjiqsvgoiqggslgiskijijijiqnoiqshsviqgsstgigoiqsvgtspsriqshiqspshgniqgqstgigpslsjijqmqmnlsjspstiqnoiqsgstgniqsvgoiqslggsjiqgqgislgqstgigngoiqshsjsniqsgstgniqshiqsnslsvstgpgnsospiqshsjsosvshsuiuiqnoigsviqgqgistgngngoqmsvgtspsriqspstgignshsosjiqgnsrshgniqsogniggpiqsgslsosjsgiqgnsliqsistiqshiqspshgnijqmqmnigtgniqsogniggpiqsjslgniqsusoskstiqnoiqsnslsjiggniqsusoskstiqsnslsggpiqstsognsrstgiihiqnhspgngtshsusugoiuiqnoiqsssosjsniqgnsrstiqggsrslsustqmsosnstshiqslssiqspshgniviqshsjsniqsnslsgivgqstgigpslsjiqgpgqsusogniqgnsliqsistiqsngtsvsiijijijqmqmtgsrgoiqsjslgniqsusoskstiqsislgnsrpliqnoiqsusoskstiqsislgnsrihqmtnsrstgistiqsogpiqsjsliqgistshgpslsjiqgnsliqsvshskstiqgnsrsogpiqshgisisogngishgigoiqsnsogpgnsosjspgnsoslsjihqmqmnoiqsusoskstiqsrslggiqnoiqsvshsnstiqsistsosjsgiqsosjsnstspsogpsogsstiqsvgoiqstsjgnsogistiqgqstgigpslsjshsusogngoijqmnjsliqsvshgngnstgiiqggsrstgistiqgoslgtiqsuslslskiuiqgoslgtiqspshsjiqgpststiqgnsrstiqstssssstspgngpiqslssiqsognijqmqmnistiqsogniqslgqsosjsoslsjgpiuiqgqgistssstgistsjspstgpiuiqsvstgnsrslsngpiqslssiqggslgisksosjsgiuiqslgiiqgpstgrgtshsusogngoiqivqmnoiqshsuggshgogpiqsssosjsniqshiqggshgoiqgnsliqggstshgpstsuiqslgtgniqslssiqsvshsksosjsgiqspsrslsospstgpijpunqqm"),
]);
curTopic = 0;
